# Generated by Django 4.2 on 2024-04-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("userInfo", "0002_alter_customuser_options_customuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("category", models.CharField(max_length=32, verbose_name="分类")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="发布时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除状态")),
                (
                    "img",
                    models.CharField(blank=True, max_length=255, verbose_name="图片链接"),
                ),
                ("ViewNum", models.IntegerField(default=0, verbose_name="浏览量")),
                ("LikeNum", models.IntegerField(default=0, verbose_name="点赞量")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="发布时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="作者",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymforum.post",
                        verbose_name="帖子",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子点赞",
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="发布时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除状态")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="评论者",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymforum.post",
                        verbose_name="帖子",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子评论",
            },
        ),
        migrations.CreateModel(
            name="PostCollect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="发布时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="作者",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymforum.post",
                        verbose_name="帖子",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子收藏",
            },
        ),
    ]
