# Generated by Django 4.2 on 2024-05-06 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ymforum", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcollect",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="updated_at",
        ),
    ]
