# Generated by Django 4.2 on 2024-04-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("userInfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("abstract", models.TextField(verbose_name="摘要")),
                ("category", models.CharField(max_length=32, verbose_name="分类")),
                (
                    "tag1",
                    models.CharField(
                        blank=True, default="考研", max_length=32, verbose_name="标签1"
                    ),
                ),
                (
                    "tag2",
                    models.CharField(
                        blank=True, default="顺利", max_length=32, verbose_name="标签2"
                    ),
                ),
                (
                    "tag3",
                    models.CharField(
                        blank=True, default="上岸", max_length=32, verbose_name="标签3"
                    ),
                ),
                ("ViewNum", models.IntegerField(default=0, verbose_name="浏览量")),
                ("LikeNum", models.IntegerField(default=0, verbose_name="点赞量")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除状态")),
                ("is_vip", models.BooleanField(default=False, verbose_name="VIP专属")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="作者",
                    ),
                ),
            ],
        ),
    ]
