# Generated by Django 4.2 on 2024-04-14 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ymblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "文章"},
        ),
    ]
