# Generated by Django 4.2 on 2024-04-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userInfo", "0002_alter_customuser_options_customuser_avatar"),
        ("ymblog", "0002_alter_article_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymblog.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览记录",
            },
        ),
        migrations.CreateModel(
            name="LikeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymblog.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "点赞记录",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "comment_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除状态")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymblog.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章评论",
            },
        ),
        migrations.CreateModel(
            name="CollectArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collect_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ymblog.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userInfo.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏记录",
            },
        ),
    ]
