# Generated by Django 4.2 on 2024-04-14 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ymblog", "0003_viewarticle_likearticle_comment_collectarticle"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ViewArticle",
        ),
    ]
