# Generated by Django 4.2 on 2024-04-08 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="用户", max_length=64, verbose_name="用户名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=13, unique=True, verbose_name="电话"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "is_active",
                    models.BooleanField(blank=True, default=True, verbose_name="激活状态"),
                ),
                (
                    "is_vip",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="是否是VIP"
                    ),
                ),
                ("ymvalue", models.IntegerField(default=0, verbose_name="研梦值")),
                (
                    "create_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
        ),
    ]
