# Generated by Django 4.2 on 2024-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userInfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "研梦用户"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="/media/avator/defaultavator.svg",
                max_length=255,
                verbose_name="头像",
            ),
        ),
    ]
