# Generated by Django 4.2 on 2024-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="scrapyArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("content", models.TextField(verbose_name="文本内容")),
                (
                    "category",
                    models.CharField(
                        blank=True, default="中性", max_length=32, verbose_name="性质"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="跳转链接"),
                ),
            ],
            options={
                "verbose_name": "爬虫文章",
            },
        ),
    ]
