# Generated by Django 4.2 on 2024-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapyarticle",
            name="emotion",
            field=models.CharField(
                blank=True, default="中性", max_length=32, verbose_name="情感"
            ),
        ),
        migrations.AlterField(
            model_name="scrapyarticle",
            name="category",
            field=models.CharField(max_length=32, verbose_name="分类"),
        ),
    ]
